server:
  #port 服务器开启端口
  port: 8000
  #mod 服务器运行模式 0-debug 1-release
  mod: 0
database:
  #host 数据库主机地址
  host: 162.14.115.114
  #port 数据库开启端口
  port: 3306
  #username 数据库账号
  username: root
  #password 数据库密码
  password: 8023Qiao
  #dbname 数据库名
  dbname: bank
  #charset 字符集
  charset: utf8
jwt:
  #secret jwt密钥
  secret: 0C018992A72AAD2FDA3F3FE2D5D9E598
redis:
  #db redis 服务器选择
  db: 0
  #addr redis 地址
  addr: 162.14.115.114:6379
  #password redis 密码
  password: 8023Qiao
sms:
  secretID : AKIDBHAwXIqBH8kBRYYbVCeqpZ8cL1VpBOOH
  secretKey : kR8eyEG4fEqW5QWP4VhdKrEUcbS9h6MS
  appID : 1305072851
  signature: 宜宾万重山网络
  templateID: 1143189
oss:
  endpoint: oss-cn-chengdu.aliyuncs.com
  bucketname: school-serve
  accessKeyID: LTAI5tDcdPqNKC82HkHCmYZ9
  accessKeySecret: sxxPdgnk34XSaRnQM19d2EZtw6lC1B
dir:
  #log_dir 日志输出目录
  log_dir: ./log
rabbitmq:
  username: qiaohuhu
  password: 8023qiao
  host: 162.14.115.114
